# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           komac
# TODO: increment version number when preparing release
Version:        2.4.0
Release:        1%{?dist}
Summary:        Manifest creator for winget-pkgs

SourceLicense:  GPL-3.0-or-later
%global _license %{shrink:
(Apache-2.0 OR MIT) AND BSD-3-Clause
(MIT OR Apache-2.0) AND Unicode-DFS-2016
GPL-3.0-or-later
0BSD OR Apache-2.0 OR MIT
Apache-2.0
Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT
Apache-2.0 OR BSD-2-Clause OR MIT
Apache-2.0 OR BSL-1.0
Apache-2.0 OR GPL-3.0
Apache-2.0 OR ISC OR MIT
Apache-2.0 OR MIT
Apache-2.0 OR MIT OR Zlib
Apache-2.0 WITH LLVM-exception
BSD-2-Clause
BSD-3-Clause
BSD-3-Clause OR GPL-2.0-only
BSL-1.0
ISC AND MIT AND OpenSSL
GPL-3.0-or-later
ISC
MIT
MIT OR Unlicense
MPL-2.0
Zlib
}
License: %_license


URL:            https://github.com/russellbanks/Komac
# TODO : download the source tarball for the verson, remove all .iss files in /assets and repackage it
Source:         Komac

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A manifest creator for winget-pkgs.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%doc README.md
%{_bindir}/komac

%changelog
%autochangelog
