name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - russellbanks
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you noticed.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Command used
      description: |
        Please copy and paste the **exact command** you ran that triggered the issue.
      placeholder: komac update Package.Identifier --version 1.2.3 --urls https://example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
