blank_issues_enabled: true
contact_links:
  - name: 查看源仓库中的问题
    url: https://github.com/russellbanks/Komac/issues
    about: 请确保你已经查看了源仓库中的问题。
  - name: 查看当前打开的问题
    url: https://github.com/DuckDuckStudio/Komac/issues
    about: 请确保你已经查看了本仓库当前打开的问题。
