name: 'Feature Request'
description: Request a new feature
title: '[Feature/Idea]: '
labels: [feat]
assignees: russellbanks
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: textarea
    attributes:
      label: What would you like to see changed/added?
      description: Try to give some examples to make it really clear!
      placeholder: Tell us what you would like to see! Something new and amazing!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Do you have any workable/viable ways?
      description: Try to give some examples to make it easy to resolve!
      placeholder: Tell us your idea!
    validations:
      required: false
